// <auto-generated />
namespace SuperSupremeMegaStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class columnfirstname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnfirstname));
        
        string IMigrationMetadata.Id
        {
            get { return "201608061904098_columnfirstname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
